"""真 PostgreSQL 上的用量库验证，默认跳过；只写并清理随机 schema。

守的是内存 SQLite 证明不了的那些：记录真的落进**独立库**、索引与唯一约束真的建在库上、
时刻列带时区且按 UTC 解释、业务库的迁移链看不到用量表。

运行规矩（见 ``docs/specs/0001-llm-usage-statistics.md`` 的「真 PostgreSQL 层」）：首次交付前
跑一次；之后改动碰到用量库相关的东西（表结构与迁移、采集器的落库路径）时重跑；其它需求的
回归不必跑。

它需要一个**独立的**连接串变量指向用量测试库——复用业务库那个变量是不行的，用量在另一个库。
它还会用只读方式读业务库（当前配置的 ``DATABASE_URL``），核对业务库里没有这张表。
"""

import asyncio
import os
import sys
from datetime import UTC, datetime
from pathlib import Path
from types import SimpleNamespace
from uuid import uuid4

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from langchain_core.messages import AIMessage, HumanMessage
from langgraph.checkpoint.memory import InMemorySaver
from sqlalchemy import MetaData, NullPool, func, select, text
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine

from agent_lab.agent.context import AgentContext
from agent_lab.agent.runtime import AgentRuntime
from agent_lab.config.llm import LlmProvider, LlmSettings
from agent_lab.config.settings import get_settings
from agent_lab.usage.assembly import UsageRuntime
from agent_lab.usage.collector import NoopUsageCollector, QueuedUsageCollector
from agent_lab.usage.contracts import UsageRecord, UsageSource, UsageStatus
from agent_lab.usage.models import UsageRecordRow
from agent_lab.usage.repository import UsageRepository

from tests.agent_helpers import ScriptedChatModel, tool_call_message
from tests.agent_scope_helpers import NEWS_SCOPE
from tests.app_helpers import FakeSearchRuntime, create_offline_app, send
from tests.auth_helpers import READER_ID, allow_reader


pytestmark = pytest.mark.skipif(
    os.getenv("RUN_POSTGRES_LLMOPS_INTEGRATION_TEST") != "1",
    reason="需要显式授权并设置独立的用量测试库 DSN。",
)

BACKEND_ROOT = Path(__file__).resolve().parents[1]


def run(coroutine):
    """在 SelectorEventLoop 上执行（psycopg 异步连接在 Windows 需要它）。"""

    if sys.platform == "win32":
        with asyncio.Runner(loop_factory=asyncio.SelectorEventLoop) as runner:
            return runner.run(coroutine)
    return asyncio.run(coroutine)


def usage_database(dsn: str, schema: str):
    """建一个把 ``search_path`` 限定在随机 schema 上的引擎，避免碰开发数据。"""

    engine = create_async_engine(
        dsn,
        poolclass=NullPool,
        hide_parameters=True,
        connect_args={
            "options": f"-csearch_path={schema} -cstatement_timeout=10000 -ctimezone=UTC",
            "connect_timeout": 5,
        },
    )
    return engine, async_sessionmaker(engine, expire_on_commit=False)


@pytest.fixture
def usage_schema():
    """建随机 schema、在里面跑一遍**用量库自己的**迁移，退出时整块删掉。"""

    dsn = os.environ.get("LLMOPS_TEST_DATABASE_URL", "")
    if not dsn.startswith("postgresql+psycopg://"):
        pytest.fail(
            "必须提供 LLMOPS_TEST_DATABASE_URL（允许随机 schema 的用量测试库）。",
            pytrace=False,
        )
    schema = f"usage_test_{uuid4().hex}"
    engine, sessions = usage_database(dsn, schema)
    config = Config()
    config.set_main_option("script_location", str(BACKEND_ROOT / "usage_migrations"))

    def upgrade(connection) -> None:
        config.attributes["connection"] = connection
        command.upgrade(config, "head")

    async def create() -> None:
        async with engine.begin() as connection:
            await connection.execute(text(f'CREATE SCHEMA "{schema}"'))
            # 用真实的用量库迁移建表，而不是 create_all：迁移文件本身也要被验证。
            await connection.run_sync(upgrade)

    async def cleanup() -> None:
        try:
            async with engine.begin() as connection:
                await connection.execute(text(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE'))
        finally:
            await engine.dispose()

    run(create())
    try:
        yield SimpleNamespace(engine=engine, sessions=sessions, schema=schema)
    finally:
        run(cleanup())


def make_record(**overrides) -> UsageRecord:
    """造一条字段齐全的用量记录。"""

    defaults = {
        "user_id": uuid4(),
        "thread_id": uuid4(),
        "run_id": uuid4(),
        "model_name": "usage-integration-model",
        "input_tokens": 10,
        "output_tokens": 4,
        "cached_tokens": 6,
        "total_tokens": 14,
        "duration_ms": 123,
        "status": UsageStatus.COMPLETED,
        "source": UsageSource.UPSTREAM,
        "occurred_at": datetime(2026, 3, 1, 12, 0, tzinfo=UTC),
    }
    return UsageRecord(**{**defaults, **overrides})


async def insert(sessions, record: UsageRecord) -> None:
    """通过仓储写一条并提交。"""

    async with sessions() as session:
        await UsageRepository(session).add(record)
        await session.commit()


def test_a_record_really_lands_in_the_separate_usage_database(usage_schema) -> None:
    """记录带着账号、会话、运行三个引用与全部约定字段落进独立库。"""

    async def scenario() -> tuple[UsageRecord, UsageRecordRow]:
        record = make_record()
        await insert(usage_schema.sessions, record)
        async with usage_schema.sessions() as session:
            row = (await session.execute(select(UsageRecordRow))).scalar_one()
        return record, row

    record, row = run(scenario())

    assert row.call_id == record.call_id
    assert (row.user_id, row.thread_id, row.run_id) == (record.user_id, record.thread_id, record.run_id)
    assert row.model_name == record.model_name
    assert (row.input_tokens, row.output_tokens, row.cached_tokens, row.total_tokens) == (10, 4, 6, 14)


def test_the_unique_constraint_keeps_one_row_per_call_id(usage_schema) -> None:
    """同一个调用标识重复受理不会在表里多出一行。"""

    async def scenario() -> int:
        record = make_record()
        await insert(usage_schema.sessions, record)
        await insert(usage_schema.sessions, record)
        async with usage_schema.sessions() as session:
            return (await session.execute(select(func.count()).select_from(UsageRecordRow))).scalar_one()

    assert run(scenario()) == 1


def test_the_table_has_both_indexes_and_a_timezone_aware_column(usage_schema) -> None:
    """两条索引齐全，运行标识不建索引，时刻列是带时区的 timestamp。"""

    async def scenario() -> tuple[list[str], str, list[str]]:
        async with usage_schema.sessions() as session:
            indexes = [
                row[0]
                for row in (
                    await session.execute(
                        text("select indexname from pg_indexes where schemaname = :schema and tablename = 'usage_records'"),
                        {"schema": usage_schema.schema},
                    )
                ).all()
            ]
            data_type = (
                await session.execute(
                    text(
                        "select data_type from information_schema.columns "
                        "where table_schema = :schema and table_name = 'usage_records' and column_name = 'occurred_at'"
                    ),
                    {"schema": usage_schema.schema},
                )
            ).scalar_one()
            session_timezone = (await session.execute(text("show timezone"))).scalar_one()
            return sorted(indexes), data_type, [session_timezone]

    indexes, data_type, session_timezone = run(scenario())

    assert "ix_usage_records_user_occurred" in indexes
    assert "ix_usage_records_user_model_occurred" in indexes
    assert "uq_usage_records_call_id" in indexes
    assert not any("run_id" in name for name in indexes), "运行标识本期不建索引"
    assert data_type == "timestamp with time zone"
    # 会话时区与列时区一起，保证写入与查询两边对「某一个 UTC 瞬间」的理解一致。
    assert session_timezone == ["UTC"]


def test_a_record_is_found_by_utc_day_boundaries(usage_schema) -> None:
    """写入一条记录后，按 UTC 的日期边界查询能查到它。"""

    async def scenario() -> list[UsageRecordRow]:
        # 23:59:30 UTC：如果写或读有一侧按别的时区解释，这条就会掉到别的「天」里去。
        await insert(
            usage_schema.sessions,
            make_record(occurred_at=datetime(2026, 3, 1, 23, 59, 30, tzinfo=UTC)),
        )
        async with usage_schema.sessions() as session:
            result = await session.execute(
                select(UsageRecordRow).where(
                    UsageRecordRow.occurred_at >= datetime(2026, 3, 1, 0, 0, tzinfo=UTC),
                    UsageRecordRow.occurred_at < datetime(2026, 3, 2, 0, 0, tzinfo=UTC),
                )
            )
            return list(result.scalars().all())

    assert len(run(scenario())) == 1


def test_the_business_database_does_not_contain_the_usage_table() -> None:
    """业务库里不存在用量表——两个库各自管自己的表结构。"""

    engine = create_async_engine(str(get_settings().database_url), poolclass=NullPool, hide_parameters=True)
    metadata = MetaData()

    async def reflect() -> list[str]:
        try:
            async with engine.connect() as connection:
                await connection.run_sync(lambda sync_connection: metadata.reflect(bind=sync_connection))
            return sorted(metadata.tables)
        finally:
            await engine.dispose()

    tables = run(reflect())

    assert "agent_threads" in tables, "反射到的应当是业务库"
    assert "usage_records" not in tables


def test_the_business_migration_chain_reports_no_usage_drift() -> None:
    """对业务库跑一次结构比对，不产生任何与用量表相关的变更。

    业务侧 ``env.py`` 读的是 ``Base.metadata``；用量表要是被挂到了那份 metadata 上，这里就会
    报「库里少了一张 usage_records」——那正是分库前提被破坏的信号。
    """

    config = Config()
    config.set_main_option("script_location", str(BACKEND_ROOT / "alembic"))
    try:
        command.check(config)
    except AutogenerateDiffsDetected as exc:
        assert "usage_records" not in str(exc), f"业务库结构比对出现了用量表：{exc}"


class NamedScriptedModel(ScriptedChatModel):
    """带模型名的假模型；``_get_ls_params`` 会把它当成 ``ls_model_name``。"""

    model_name: str = "usage-integration-model"


class EmptySearchService:
    """返回空结果的假检索服务，只为让搜索工具能真的被执行一次。"""

    async def search_documents(self, request, *, resolved_scope):
        return []


def test_a_conversation_writes_one_row_per_call_sharing_the_run_identity(usage_schema) -> None:
    """在真库上跑一次真实对话：每次模型调用一行，同一次运行的记录共享运行标识。

    这一次两轮模型调用：第一轮决定调检索工具（上游没报用量，来源记缺失），第二轮给出回答
    （上游报了用量）。它一次性盖上四个验收点：真库落库、账号与会话引用、同运行同一运行标识、
    以及「上游没报」与「上游报了值」在真库上仍然分得开。
    """

    async def scenario():
        collector = QueuedUsageCollector(
            session_factory=usage_schema.sessions,
            loop=asyncio.get_running_loop(),
            # 排空时限放宽：真库在跨网络链路上，一次提交要一秒以上，而生产默认的排空上限
            # 就是一次刷写间隔（1 秒）。这里要验的是「记录真的落进独立库」，不是关停时限。
            drain_timeout=30.0,
        )
        model = NamedScriptedModel(
            responses=[
                tool_call_message("search_documents", {"query": "央行降息"}),
                AIMessage(
                    content="央行确实降息了。",
                    usage_metadata={
                        "input_tokens": 10,
                        "output_tokens": 4,
                        "total_tokens": 14,
                        "input_token_details": {"cache_read": 6},
                    },
                ),
            ]
        )
        runtime = AgentRuntime.build(
            llm_settings=LlmSettings(
                provider=LlmProvider.OLLAMA,
                base_url="http://127.0.0.1:11434",
                model="usage-integration-model",
                fallback_model="usage-integration-model",
            ),
            search_service=EmptySearchService(),
            session_factory=None,  # type: ignore[arg-type]
            database_url="postgresql+psycopg://unused/unused",
            checkpointer=InMemorySaver(),
            model=model,
            usage_collector=collector,
            retry_initial_delay=0.0,
        )
        user_id, thread_id = uuid4(), uuid4()
        context = AgentContext(scope=NEWS_SCOPE, user_id=user_id, thread_id=thread_id)
        await runtime.graph.ainvoke(
            {"messages": [HumanMessage(content="央行降息了吗")]},
            config={"configurable": {"thread_id": str(uuid4())}},
            context=context,
        )
        await collector.drain()
        async with usage_schema.sessions() as session:
            stored = list(
                (await session.execute(select(UsageRecordRow).order_by(UsageRecordRow.id)))
                .scalars()
                .all()
            )
        return model, context, user_id, thread_id, stored

    model, context, user_id, thread_id, stored = run(scenario())

    assert model.call_count == 2
    assert len(stored) == 2, "一次模型调用一条，不多不少"
    assert {row.run_id for row in stored} == {context.run_id}
    assert {row.user_id for row in stored} == {user_id}
    assert {row.thread_id for row in stored} == {thread_id}

    without_usage = next(row for row in stored if row.source == UsageSource.MISSING.value)
    with_usage = next(row for row in stored if row.source == UsageSource.UPSTREAM.value)
    assert without_usage.status == UsageStatus.COMPLETED.value
    assert without_usage.source == UsageSource.MISSING.value, "上游没报用量要记成缺失"
    assert (without_usage.input_tokens, without_usage.total_tokens) == (0, 0)
    assert with_usage.source == UsageSource.UPSTREAM.value
    assert (with_usage.input_tokens, with_usage.output_tokens, with_usage.total_tokens) == (10, 4, 14)
    assert with_usage.cached_tokens == 6
    assert with_usage.model_name == "usage-integration-model"
    assert with_usage.duration_ms >= 0
    assert with_usage.occurred_at.tzinfo is not None


def test_the_detail_api_reads_records_after_the_migration_ran(usage_schema) -> None:
    """照部署流程建完表之后，明细接口能从真库读出记录。

    这一条把「表存在」与「接口能读」接起来：迁移建的就是接口查询实际用的那张表。它只把用量库
    换成真的，认证与模型都是内存替身。
    """

    record = make_record(user_id=READER_ID)

    async def scenario() -> list[dict]:
        await insert(usage_schema.sessions, record)
        usage_runtime = UsageRuntime(
            engine=usage_schema.engine,
            session_factory=usage_schema.sessions,
            collector=NoopUsageCollector(),
        )
        app = create_offline_app(
            runtime_factory=FakeSearchRuntime,
            usage_runtime_factory=lambda: usage_runtime,
        )
        allow_reader(app)
        response = await send(app, "GET", "/usage/records")
        assert response.status_code == 200
        return response.json()["items"]

    items = run(scenario())

    assert [item["call_id"] for item in items] == [str(record.call_id)]
    assert items[0]["model_name"] == record.model_name
